### ISSUE TITLE
Find reference transcript targeted by scoreset submission

### ISSUE THREAD

**Issue by samriddhi99** [ave-dcd/dcd_mapping#19]
- [x] Query UTA for all transcripts that have alignments overlapping our alignment using the hit locations and chromosome obtained from BLAT Alignment.
- [x] From those transcripts, select for those that are compatible (there are no exons missing from the target sequence alignment to the genome)
- [x] Select the favored representative transcript using our previously established process (i.e. MANE Select / Plus Clinical / Longest). 
- [x] Code to select using MANE Select / Plus Clinical
- [x] Code for Longest Compatible
- [x] Obtain gene symbol from MANE transcripts

**Comment by ahwagner** [comment]
@samriddhi99 is an "hgnc accession value" an HGNC id, e.g. `hgnc:1234`? Our goal for this project should be to validate and map a submitted score set; does a method to retrieve HGNC ids help us with that goal? Use this GitHub issue to provide rationale for why we want to retrieve gene accessions.

**Comment by ahwagner** [comment]
After discussion, this issue is really focused on how we can get to our preferred, compatible transcript for protein-coding scoresets. This has 3 primary steps:

1. Query UTA for all transcripts that have alignments overlapping our alignment
2. From those transcripts, select for those that are compatible (there are no exons missing from the target sequence alignment to the genome)
3. Select the favored representative transcript using our previously established process (i.e. MANE Select / Plus Clinical / Longest).

@jarbesfeld should be primary assist on this, @korikuzma can also assist where needed.
